[build]
  command = "yarn build"
  publish = "_site/"

[[redirects]]
from = "/flexbox"
to = "/css-flexbox"

[[redirects]]
from = "/flowtype"
to = "/flow"

[[redirects]]
from = "/gpgconf"
to = "/gnupg"

[[redirects]]
from = "/gpg"
to = "/gnupg"

[[redirects]]
from = "/gutom"
to = "/ph-food-delivery"

[[redirects]]
from = "/handlebars-js"
to = "/handlebars.js"

[[redirects]]
from = "/harvey-js"
to = "/harvey.js"

[[redirects]]
from = "/immutable-js"
to = "/immutable.js"

[[redirects]]
from = "/jade"
to = "/pug"

[[redirects]]
from = "/package"
to = "/package-json"

[[redirects]]
from = "/package.json"
to = "/package-json"

[[redirects]]
from = "/phoenix-ecto@1.3"
to = "/phoenix-ecto"

[[redirects]]
from = "/sh"
to = "/bash"

[[redirects]]
from = "/commander-js"
to = "/commander.js"

[[redirects]]
from = "/es2015"
to = "/es6"

[[redirects]]
from = "/es2016"
to = "/es6"

[[redirects]]
from = "/es2017"
to = "/es6"

[[redirects]]
from = "/es2018"
to = "/es6"

[[redirects]]
from = "/expect.js"
to = "/expectjs"

[[redirects]]
from = "/factory_girl"
to = "/factory_bot"

[[redirects]]
from = "/css-animation"
to = "/css#animation"

[[redirects]]
from = "/css-background"
to = "/css#background"

[[redirects]]
from = "/css-font"
to = "/css#fonts"

[[redirects]]
from = "/css-selectors"
to = "/css#selectors"

[[redirects]]
from = "/brew"
to = "/homebrew"

[[redirects]]
from = "/date"
to = "/datetime"

[[redirects]]
from = "/fetch"
to = "/js-fetch"
